" plugins
filetype plugin indent on
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')

"""
" utility
"""
" fzf
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
" filer
Plug 'cocopon/vaffle.vim'
" sandwich
Plug 'machakann/vim-sandwich'
" auto close
Plug 'mattn/vim-lexiv'
" jump
Plug 'easymotion/vim-easymotion'
" comment out
Plug 'tyru/caw.vim'
" replace
Plug 'markonm/traces.vim'

"""
" view
"""
" color scheme
Plug 'kaicataldo/material.vim', { 'branch': 'main' }
" statusline
Plug 'itchyny/lightline.vim'

"""
" git
"""
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'

"""
" languages
"""
" vim-lsp
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'

" go
Plug 'sebdah/vim-delve'
Plug 'mattn/vim-goimports'
" slim
Plug 'slim-template/vim-slim'
" coffee
Plug 'kchmck/vim-coffee-script'
" js
Plug 'prettier/vim-prettier', { 'do': 'yarn install' }

call plug#end()

" load settings
runtime! _config/init/*.vim
runtime! _config/plugins/*.vim
runtime! _config/languages/*.vim
" call map(sort(split(globpath(&runtimepath, '_config/**/*.vim'))), {->[execute('exec "so" v:val')]})

