" plugins
filetype plugin indent on
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin('~/.vim/plugged')

"""
" utility
"""
" ctrl-p
" fzf
" Plug 'ctrlpvim/ctrlp.vim'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
" filer
Plug 'cocopon/vaffle.vim'
" sandwich
" Plug 'machakann/vim-sandwich'
" auto close
Plug 'mattn/vim-lexiv'
" jump
Plug 'easymotion/vim-easymotion'
" comment out
Plug 'tyru/caw.vim'
" replace
Plug 'markonm/traces.vim'

"""
" view
"""
" color scheme
" Plug 'kaicataldo/material.vim', { 'branch': 'main' }
Plug 'ghifarit53/tokyonight-vim'
" statusline
Plug 'itchyny/lightline.vim'

"""
" git
"""
Plug 'airblade/vim-gitgutter'
Plug 'tpope/vim-fugitive'
" tig
Plug 'iberianpig/tig-explorer.vim'
Plug 'rbgrouleff/bclose.vim'

"""
" language server
"""
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'neoclide/coc-snippets', {'do': 'yarn install --frozen-lockfile'}
Plug 'josa42/coc-go', {'do': 'yarn install --frozen-lockfile'}
Plug 'neoclide/coc-solargraph', {'do': 'yarn install --frozen-lockfile'}
Plug 'neoclide/coc-tsserver', {'do': 'yarn install --frozen-lockfile'}
Plug 'neoclide/coc-prettier', {'do': 'yarn install --frozen-lockfile'}
Plug 'neoclide/coc-eslint', {'do': 'yarn install --frozen-lockfile'}
Plug 'neoclide/coc-html', {'do': 'yarn install --frozen-lockfile'}
Plug 'honza/vim-snippets'
"""
" languages
"""
" go
Plug 'sebdah/vim-delve'
Plug 'mattn/vim-goimports'
" slim
Plug 'slim-template/vim-slim'
" coffee
Plug 'kchmck/vim-coffee-script'
" ts
Plug 'leafgarland/typescript-vim'

call plug#end()

" load settings
runtime! _config/init/*.vim
runtime! _config/plugins/*.vim
runtime! _config/languages/*.vim
